### ISSUE TITLE
Incoming packets not received with sockets using SO_ATTACH_REUSEPORT_CBPF

### ISSUE THREAD

**Issue by estaban** [amzn/amzn-drivers#103]
I have a multi-threaded UDP server, all listening threads are bound to the same port using SO_REUSEPORT. I am overriding the load balancing algorithm via SO_ATTACH_REUSEPORT_CBPF, the dispatching function is simply the core number the interrupt is being processed on.

Incoming UDP datagrams larger than rx_copybreak minus the IP header are not being received by the application (tested with multiple values of rx_copybreak). However, datagrams smaller than that threshold are successfully received by the application.

I am using RHEL 5.3, and ena driver version 2.0.3g on a C5 EC2 instance. I confirmed that the same code run on a machine with ixgbe driver was working for all datagram sizes.

**Comment by gtzalik** [comment]
@estaban Thanks for contacting us
We will investigate it and will let you know about our findings.

**Comment by sameehj** [comment]
Hi @estaban ,

Thank you for reporting this, I'll be working on this with you for resolving the issue.

We ran some sanity checks with some packet generator to make sure this doesn't happen in each
and every scenario and indeed it didn't reproduce with udp traffic with various UDP datagram sizes.

In order to make this efficient, can you please contact me through my email address <sameehj@amazon.com> so that we continue investigating the issue offline. I need you to provide me with more information on how to reproduce this.

Thanks,
Sameeh

**Comment by sameehj** [comment]
The solution for this issue is the same as the solution for https://github.com/amzn/amzn-drivers/issues/137
Therefore closing this issue as a duplicate.
