### ISSUE TITLE
[Feature request]: Upstream Linux EFA GDR Support

### ISSUE THREAD

**Issue by sdodson** [amzn/amzn-drivers#282]
### Preliminary Actions

- [X] I have searched the existing [issues](https://github.com/amzn/amzn-drivers/issues) and didn't find a duplicate.

### Driver Type

Linux kernel driver for Elastic Fabric Adapter (EFA)

### Motivation

Unless I'm mistaken the GPU Direct Support is only possible with the out of tree driver. It would be nice if GDR support was added to Linux in tree driver.

### Solution

Upstream GDR support

**Comment by mrgolin** [comment]
Hi @sdodson,
Thanks for reaching out.

Actually GPU Direct is already supported in this code and in the Linux in tree EFA driver using dma-buf mechanism as a way of passing memory for registration. This can be used with Nvidia and Trainium accelerators' latest drivers. In addition, out of tree EFA driver supports MR registration using P2P interface, but this can't be upstreamed since it is dependent on Nvidia out of tree driver. 

Please feel free to follow up with additional questions.

**Comment by sdodson** [comment]
Thanks, I'll work on checking with dma-buff support.
