### ISSUE TITLE
Performance in terms of PPS

### ISSUE THREAD

**Issue by adam-kulagowski** [amzn/amzn-drivers#68]
Hi,

I'm trying to use Amazon ENA to generate RFC2544 in our solution. However on c5.9xlarge Ubuntu I can only get up to 500k PPS (64B of UDP packet) with CPU ~2% . Anything higher the CPU skyrockets up to 100% and I'm getting packet losses.

The flow is build from one UDP packet and it is send between two interfaces (eni-d4765480 and eni-d6765482). Both of them are connected to the same EC2 instance. The Instance ID is i-04485508cf26bfcf6 (eu-central-1).

To generate the traffic I was using Trex or pktgen. Both of them are using DPDK.

Are those numbers expected? If so is there any way to get ~5MPPS performance on AWS?

Regards,
Adam

**Comment by AWSNB** [comment]
Thanks Adam for trying out C5

C5 should get much more than this

I'm curious if you are running single flow and if you tried multi-flow ?
And If running multi-flow, how many running concurrently ?

feel free to ping us at zorik@amazon.com for further debug

**Comment by adam-kulagowski** [comment]
Sure - I've sent You an email and I'll try to post an update here at the end.

**Comment by bfeinberg43** [comment]
What was the outcome here?  UDP PPS is a critical performance driver for our AWS solutions as well.

**Comment by sasingam** [comment]
What was the outcome of this issue ?
We are also seeing similar issue on c5.4xlarge & c5n.4xlarge instances when DPDK-19.11.2 is used. 
Even DPDK's Testpmd application is not able to go beyond  700K PPS  at rx side on c5.4xlarge when 8 RX queues and 8 forwarding cores are used.

**Comment by I-gor-C** [comment]
@sasingam In order to better understand the issue please describe your network topology and the exact scenario.

**Comment by AWSNB** [comment]
@sasingam  the c5.4xl and c5n.4xl would have different PPS capability

is the 700K PPS you reporting for c5n.4xl as well ?

I do believe 700K PPS on c5.4xl is at the limit or close to the limit, and its not a driver issue.  to prove that, would be helpful if you can confirm perf on c5.9xl/12xl and see if that scales

for c5n.4xl, other customers report 2.5Mpps or more,  see https://github.com/amzn/amzn-drivers/issues/138

for that, need to make sure you have multiple flows,  i.e. flows with different TCP/UDP ports and/or different IP addresses

**Comment by zorikm** [comment]
@sasingam ,
We would appreciate your response.

**Comment by sasingam** [comment]
@zorikm ,
Thanks for your quick response. 

700K PPS is observed on c5.4xl . I am unable to test the same (testpmd) on c5n.4xl due to some dpdk issue. 
I have to yet to collect data on c5.9xl and 12xl
I will let you know once I collect the data on c5n.4xl, c5.9xl and c5.12xl. 

One notable improvement was recently observed in our custom DPDK application when igb_uio module was loaded with wc_activate=1 module parameter.

**Comment by nafeabshara** [comment]
Indeed need wc_activate to take advantage for perf enhancement in ENA v2.xx

We’ll look at our documentations or drivers how to help avoid this

**Comment by sasingam** [comment]
@zorikm ,
I am seeing that following are the PPS limits for c5, c5n instances. PPS limit in the below table indicates total  RX and TX PPS per instance (i.e for all the interfaces on that instance).
=======================
Instance Type   | PPS limit(RX + TX)
=======================
c5.xlarge           |  1  Million
---------------------------------------
c5.2xlarge         |  1.2 Million
---------------------------------------
c5.4xlarge         |  1.5 Million
---------------------------------------
c5n.xlarge         |  1.6 Million
---------------------------------------
c5n.2xlarge       |  3.8 Million
---------------------------------------
c5n.4xlarge       |  4.5 Million
=======================

PPS limit on c5n.xlarge may be higher than 1.6M , but due to high CPU utilization , I am not able to test beyond 1.6M. 
I just want to check if there is any scope for going beyond above reported values and it would be really helpful if you can confirm that above data is consistent with your observations i.e if the above PPS limits for c5, c5n instances are correct 

I did not test on c5.9xl, c5.12xl instances.

Your reply would be greatly appreciated.

**Comment by nafeabshara** [comment]
Hi

Are these measured numbers?  I dont believe AWS published these numbers

**Comment by sasingam** [comment]
@nafeabshara ,
Yes, AWS did not publish these numbers and these numbers are what we observed during our performance testing on AWS C5 instances with our own application.

**Comment by zorikm** [comment]
Thanks @sasingam,
The numbers seems to be in a right ballpark.
How do you measure? It seems to be (Tx+Rx) according to what you mentioned above.
What do you get with unidirectional traffic?

**Comment by sasingam** [comment]
@zorikm ,
Thanks for the reply.
I used our own application based on DPDK, which works somewhat similar like a l3fwd application but with some added functionality. 
Yes the PPS numbers I have mentioned  includes both RX and TX packets per second.

As I said, our application forwards the packets , so I cannot measure unidirectional traffic using that. I will try to tailor it for unidirectional traffic and will share the results if it works.

**Comment by I-gor-C** [comment]
@sasingam Have you managed to measure the unidirectional traffic? FYI, we have published a DPDK Test Suite that can be used for PPS measurements: https://github.com/amzn/amzn-ec2-ena-utilities/tree/main/ena-dts

**Comment by sasingam** [comment]
No, I did not get a chance to measure PPS for unidirectional traffic. 
Thanks, I will use the DPDK test suite to measure it

**Comment by I-gor-C** [comment]
Hi @sasingam 
I was a bit off with the advice to use the DPDK Test Suite. It will take some additional time to make it ready for usage, my apologies.
I will update here when it's available.

**Comment by shaibran** [comment]
@sasingam @adam-kulagowski DTS was released, you can find it under: https://github.com/amzn/amzn-ec2-ena-utilities/tree/main/ena-dts
We should update the customer
